name: CI
on:
  push:
    branches:
      - "main"

concurrency: "gradle-${{ github.ref }}"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "wrapper"
      - name: "validate version"
        run: |
          VERSION="$(./gradlew properties | awk '/^version:/ { print $2; }')"
          if ! echo "$VERSION" | grep -q 'SNAPSHOT'; then
            echo "release version detected, refusing to publish..."
            exit 1
          fi
      - name: "publish artifacts"
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_ciSigningKey: "${{ secrets.CI_SIGNING_KEY }}"
          ORG_GRADLE_PROJECT_ciSigningPassword: "${{ secrets.CI_SIGNING_PASSWORD }}"
          ORG_GRADLE_PROJECT_sonatypeUsername: "${{ secrets.SONATYPE_USERNAME }}"
          ORG_GRADLE_PROJECT_sonatypePassword: "${{ secrets.SONATYPE_PASSWORD }}"
          ORG_GRADLE_PROJECT_hyperaSnapshotsUsername: "${{ secrets.HYPERA_SNAPSHOTS_USERNAME }}"
          ORG_GRADLE_PROJECT_hyperaSnapshotsPassword: "${{ secrets.HYPERA_SNAPSHOTS_PASSWORD }}"